apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{.Chart.Name}}-{{.Chart.Version}}
  name: {{.Chart.Name}}
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
    name: {{ .Values.image.app }}
    ports:
    - containerPort: {{ .Values.service.spec.ports.containerPort }}
      protocol: {{ .Values.service.spec.ports.protocol }}
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
